fleet:
  token: nnmNHt_KHdhkEJbt9gNrHvS4uBex7tumHc99iYF4rEE
  port: 9100
  nodes:
  - name: mining-station
    host: 192.168.40.10
    port: 9100
    role: primary
  - name: node-250
    host: 192.168.40.250
    port: 9100
    role: worker
