#!/usr/bin/env bash
# =============================================================================
# AICP Fleet Management — initialize, join, status, and test fleet connectivity
#
# Usage:
#   make fleet-init                        Generate fleet token + config for this node
#   make fleet-join HOST=192.168.40.250    Add a remote node to the fleet
#   make fleet-status                      Check all fleet nodes
#   make fleet-test                        Run a task on each node to verify
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VENV_PYTHON="$REPO_ROOT/.venv/bin/python"
FLEET_CONFIG="$REPO_ROOT/config/fleet.yaml"
DEFAULT_PORT=9100

# ── Colors ────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
    RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
    CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; YELLOW=''; GREEN=''; CYAN=''; BOLD=''; RESET=''
fi

log_ok()   { echo -e "${GREEN}[OK]${RESET}    $*"; }
log_fail() { echo -e "${RED}[FAIL]${RESET}  $*" >&2; }
log_info() { echo -e "        $*"; }
log_step() { echo -e "${CYAN}[STEP]${RESET}  $*"; }
log_head() { echo -e "\n${BOLD}── $* ──${RESET}"; }
die()      { log_fail "$*"; exit 1; }

# ── Detect this machine's LAN IP ─────────────────────────────────────────────
detect_local_ip() {
    # Try to find the 192.168.x.x or 10.x.x.x IP (not WSL internal, not loopback)
    local ip
    # Method 1: ip route (most reliable on Linux)
    ip=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+' | head -1)
    if [[ -n "$ip" && "$ip" != 172.17.* && "$ip" != 127.* ]]; then
        echo "$ip"
        return
    fi
    # Method 2: hostname -I, pick first non-WSL IP
    for candidate in $(hostname -I 2>/dev/null); do
        case "$candidate" in
            192.168.*|10.*) echo "$candidate"; return ;;
        esac
    done
    # Method 3: WSL — check Windows host IP (the WSL host is the gateway)
    if grep -qi microsoft /proc/version 2>/dev/null; then
        local gateway
        gateway=$(ip route show default 2>/dev/null | awk '{print $3}' | head -1)
        if [[ -n "$gateway" ]]; then
            # The Windows host IP on the LAN — query via powershell
            local win_ip
            win_ip=$(powershell.exe -NoProfile -Command \
                "Get-NetIPAddress -AddressFamily IPv4 | Where-Object { \$_.IPAddress -like '192.168.*' -or \$_.IPAddress -like '10.*' } | Select-Object -First 1 -ExpandProperty IPAddress" \
                2>/dev/null | tr -d '\r')
            if [[ -n "$win_ip" ]]; then
                echo "$win_ip"
                return
            fi
        fi
    fi
    # Fallback
    hostname -I 2>/dev/null | awk '{print $1}'
}

# ── Generate a secure fleet token ─────────────────────────────────────────────
generate_token() {
    python3 -c "import secrets; print(secrets.token_urlsafe(32))"
}

# =============================================================================
# COMMAND: init
# =============================================================================
cmd_init() {
    log_head "Fleet initialization"

    local MY_IP
    MY_IP=$(detect_local_ip)
    local MY_NAME
    MY_NAME=$(hostname | tr '[:upper:]' '[:lower:]')

    if [[ -f "$FLEET_CONFIG" ]]; then
        log_info "Existing fleet config found at $FLEET_CONFIG"
        echo -n "Overwrite? [y/N] "
        read -r answer
        [[ "$answer" =~ ^[Yy] ]] || { log_info "Keeping existing config."; exit 0; }
    fi

    local TOKEN
    TOKEN=$(generate_token)

    log_step "Generating fleet config"
    log_info "This node:  $MY_NAME @ $MY_IP:$DEFAULT_PORT"
    log_info "Fleet token generated (shared secret for all nodes)"

    cat > "$FLEET_CONFIG" <<EOF
# AICP Fleet Configuration
# Generated by: make fleet-init
# Copy this file to each machine in config/fleet.yaml
# The token must be identical on all nodes.

fleet:
  token: "$TOKEN"
  port: $DEFAULT_PORT
  nodes:
    - name: "$MY_NAME"
      host: "$MY_IP"
      port: $DEFAULT_PORT
      role: primary
EOF

    log_ok "Fleet config written to $FLEET_CONFIG"

    # Also update default.yaml cluster section
    log_step "Updating config/default.yaml with cluster reference"
    "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

default_cfg_path = Path("config/default.yaml")
cfg = yaml.safe_load(default_cfg_path.read_text())

# Add/update cluster section pointing to fleet.yaml
cfg["cluster"] = {
    "config_file": "config/fleet.yaml",
    "auto_route": False,
}

default_cfg_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    log_ok "config/default.yaml updated with cluster reference"

    # Update .env with agent token
    if grep -q '^AICP_AGENT_SECRET=' .env 2>/dev/null; then
        sed -i "s|^AICP_AGENT_SECRET=.*|AICP_AGENT_SECRET=$TOKEN|" .env
    else
        echo "" >> .env
        echo "# ── Fleet (auto-generated by make fleet-init) ─────────────────────────────" >> .env
        echo "AICP_AGENT_SECRET=$TOKEN" >> .env
    fi
    log_ok "Agent token written to .env"

    echo ""
    echo -e "${BOLD}Next steps:${RESET}"
    echo ""
    echo "  1. Start the agent daemon on this machine:"
    echo "     make agent-up"
    echo "     (or: make install-service  for auto-start on boot)"
    echo ""
    echo "  2. Add the other machine:"
    echo "     make fleet-join HOST=192.168.40.250"
    echo ""
    echo "  3. On the other machine (192.168.40.250):"
    echo "     - Copy config/fleet.yaml to their config/fleet.yaml"
    echo "     - Run: make agent-up"
    echo ""
    echo "  4. Verify:"
    echo "     make fleet-status"
    echo ""
}

# =============================================================================
# COMMAND: join — add a remote node
# =============================================================================
cmd_join() {
    local REMOTE_HOST="${1:-}"
    local REMOTE_PORT="${2:-$DEFAULT_PORT}"
    local REMOTE_NAME="${3:-}"

    [[ -n "$REMOTE_HOST" ]] || die "Usage: make fleet-join HOST=<ip> [PORT=<port>] [NAME=<name>]"
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    if [[ -z "$REMOTE_NAME" ]]; then
        REMOTE_NAME="node-${REMOTE_HOST##*.}"
    fi

    log_head "Adding node to fleet"
    log_step "Checking connectivity to $REMOTE_HOST:$REMOTE_PORT"

    # Test basic connectivity
    if ! ping -c1 -W2 "$REMOTE_HOST" >/dev/null 2>&1; then
        log_fail "Cannot ping $REMOTE_HOST"
        log_info "Check that the machine is on and reachable on the network."
        exit 1
    fi
    log_ok "Host reachable (ping OK)"

    # Test if agent is running (3s timeout — it's OK if it's not up yet)
    local AGENT_OK=0
    if curl -sf --connect-timeout 3 --max-time 5 "http://$REMOTE_HOST:$REMOTE_PORT/health" >/dev/null 2>&1; then
        AGENT_OK=1
        log_ok "Agent daemon responding at $REMOTE_HOST:$REMOTE_PORT"
    else
        log_info "Agent not responding at $REMOTE_HOST:$REMOTE_PORT (that's OK — start it after setup)"
    fi

    # Test if LocalAI is running
    if curl -sf --connect-timeout 3 --max-time 5 "http://$REMOTE_HOST:8090/v1/models" >/dev/null 2>&1; then
        log_ok "LocalAI responding at $REMOTE_HOST:8090"
    else
        log_info "LocalAI not responding at $REMOTE_HOST:8090 (start it after setup)"
    fi

    # Check if node already exists
    if grep -q "host: \"$REMOTE_HOST\"" "$FLEET_CONFIG" 2>/dev/null || \
       grep -q "host: $REMOTE_HOST" "$FLEET_CONFIG" 2>/dev/null; then
        log_info "Node $REMOTE_HOST already in fleet config — updating"
        # Remove existing entry and re-add
        "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

fleet_path = Path("$FLEET_CONFIG")
cfg = yaml.safe_load(fleet_path.read_text())

# Remove existing node with same host
cfg["fleet"]["nodes"] = [
    n for n in cfg["fleet"].get("nodes", [])
    if n.get("host") != "$REMOTE_HOST"
]

# Add updated entry
cfg["fleet"]["nodes"].append({
    "name": "$REMOTE_NAME",
    "host": "$REMOTE_HOST",
    "port": $REMOTE_PORT,
    "role": "worker",
})

fleet_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    else
        # Append new node
        "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

fleet_path = Path("$FLEET_CONFIG")
cfg = yaml.safe_load(fleet_path.read_text())

cfg["fleet"]["nodes"].append({
    "name": "$REMOTE_NAME",
    "host": "$REMOTE_HOST",
    "port": $REMOTE_PORT,
    "role": "worker",
})

fleet_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    fi
    log_ok "Node $REMOTE_NAME ($REMOTE_HOST:$REMOTE_PORT) added to fleet config"

    # Show the fleet config
    echo ""
    echo -e "${BOLD}Fleet config ($FLEET_CONFIG):${RESET}"
    cat "$FLEET_CONFIG"

    echo ""
    echo -e "${BOLD}Next steps for the remote machine ($REMOTE_HOST):${RESET}"
    echo ""
    echo "  1. Copy the fleet config:"
    echo "     scp config/fleet.yaml $REMOTE_HOST:~/devops-expert-local-ai/config/fleet.yaml"
    echo ""
    echo "  2. Copy the agent token to their .env:"
    FLEET_TOKEN=$(grep 'token:' "$FLEET_CONFIG" | head -1 | awk '{print $2}' | tr -d '"')
    echo "     ssh $REMOTE_HOST 'echo AICP_AGENT_SECRET=$FLEET_TOKEN >> ~/devops-expert-local-ai/.env'"
    echo ""
    echo "  3. Start the agent on the remote machine:"
    echo "     ssh $REMOTE_HOST 'cd ~/devops-expert-local-ai && make agent-up'"
    echo ""
    echo "  4. Verify fleet:"
    echo "     make fleet-status"
    echo ""
}

# =============================================================================
# COMMAND: status — check all nodes
# =============================================================================
cmd_status() {
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    log_head "Fleet status"

    "$VENV_PYTHON" - <<'PYEOF'
import yaml
import sys
sys.path.insert(0, ".")

from pathlib import Path
from aicp.agent.client import AgentClient

fleet_path = Path("config/fleet.yaml")
cfg = yaml.safe_load(fleet_path.read_text())
fleet = cfg.get("fleet", {})
token = fleet.get("token", "")
nodes = fleet.get("nodes", [])

if not nodes:
    print("  No nodes configured. Run: make fleet-join HOST=<ip>")
    sys.exit(0)

print(f"  Fleet: {len(nodes)} node(s)\n")

for node in nodes:
    name = node["name"]
    host = node["host"]
    port = node.get("port", 9100)
    role = node.get("role", "worker")

    client = AgentClient(host, port, token)

    # Check agent health
    agent_ok = client.health()

    # Check LocalAI
    import httpx
    localai_ok = False
    models = []
    try:
        r = httpx.get(f"http://{host}:8090/v1/models", timeout=3.0)
        if r.status_code == 200:
            localai_ok = True
            models = [m["id"] for m in r.json().get("data", [])]
    except Exception:
        pass

    # Check GPU
    gpu_info = ""
    if agent_ok:
        status = client.status()
        if status and status.get("gpus"):
            g = status["gpus"][0]
            gpu_info = f"{g.get('name', '?')} ({g.get('vram_free_mb', '?')}MB free / {g.get('vram_total_mb', '?')}MB)"

    # Print
    agent_sym = "\033[0;32m●\033[0m" if agent_ok else "\033[0;31m●\033[0m"
    localai_sym = "\033[0;32m●\033[0m" if localai_ok else "\033[0;31m●\033[0m"

    print(f"  {name} ({host}:{port}) [{role}]")
    print(f"    Agent:   {agent_sym} {'online' if agent_ok else 'offline'}")
    print(f"    LocalAI: {localai_sym} {'online' if localai_ok else 'offline'}" +
          (f"  models: {', '.join(models)}" if models else ""))
    if gpu_info:
        print(f"    GPU:     {gpu_info}")
    print()

PYEOF
}

# =============================================================================
# COMMAND: test — run a task on each node
# =============================================================================
cmd_test() {
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    log_head "Fleet connectivity test"

    "$VENV_PYTHON" - <<'PYEOF'
import yaml
import json
import time
import sys
sys.path.insert(0, ".")

from pathlib import Path
from aicp.agent.client import AgentClient

fleet_path = Path("config/fleet.yaml")
cfg = yaml.safe_load(fleet_path.read_text())
fleet = cfg.get("fleet", {})
token = fleet.get("token", "")
nodes = fleet.get("nodes", [])

for node in nodes:
    name = node["name"]
    host = node["host"]
    port = node.get("port", 9100)

    print(f"  Testing {name} ({host}:{port})...")
    client = AgentClient(host, port, token)

    if not client.health():
        print(f"    \033[0;31m✗ Agent not responding\033[0m")
        continue

    try:
        start = time.time()
        result = client.execute_task(
            prompt="Reply with exactly: FLEET_TEST_OK",
            mode="think",
            backend="local",
        )
        elapsed = time.time() - start
        text = result.get("result", "")
        if "FLEET_TEST_OK" in text or len(text) > 0:
            print(f"    \033[0;32m✓ Task executed in {elapsed:.1f}s\033[0m")
            print(f"    Response: {text[:100]}")
        else:
            print(f"    \033[0;33m⚠ Got empty response\033[0m")
    except Exception as e:
        print(f"    \033[0;31m✗ Task failed: {e}\033[0m")

    print()

PYEOF
}

# =============================================================================
# COMMAND: copy-config — helper to scp fleet.yaml to a remote node
# =============================================================================
cmd_copy() {
    local REMOTE_HOST="${1:-}"
    [[ -n "$REMOTE_HOST" ]] || die "Usage: make fleet-copy HOST=<ip>"
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    FLEET_TOKEN=$(grep 'token:' "$FLEET_CONFIG" | head -1 | awk '{print $2}' | tr -d '"')

    log_head "Copying fleet config to $REMOTE_HOST"

    log_step "Copying config/fleet.yaml"
    scp "$FLEET_CONFIG" "$REMOTE_HOST:~/devops-expert-local-ai/config/fleet.yaml"
    log_ok "fleet.yaml copied"

    log_step "Setting agent token in remote .env"
    ssh "$REMOTE_HOST" "cd ~/devops-expert-local-ai && \
        grep -q '^AICP_AGENT_SECRET=' .env 2>/dev/null && \
        sed -i 's|^AICP_AGENT_SECRET=.*|AICP_AGENT_SECRET=$FLEET_TOKEN|' .env || \
        echo 'AICP_AGENT_SECRET=$FLEET_TOKEN' >> .env"
    log_ok "Agent token set on remote"

    echo ""
    echo -e "${BOLD}Done. Now start the agent on $REMOTE_HOST:${RESET}"
    echo "  ssh $REMOTE_HOST 'cd ~/devops-expert-local-ai && make agent-up'"
    echo ""
}

# =============================================================================
# Dispatch
# =============================================================================
CMD="${1:-}"
shift || true

case "$CMD" in
    init)    cmd_init ;;
    join)    cmd_join "${HOST:-${1:-}}" "${PORT:-$DEFAULT_PORT}" "${FLEET_NAME:-}" ;;
    status)  cmd_status ;;
    test)    cmd_test ;;
    copy)    cmd_copy "${HOST:-$1}" ;;
    *)
        echo "Usage: scripts/fleet.sh <command>"
        echo ""
        echo "Commands:"
        echo "  init                 Generate fleet token + config for this node"
        echo "  join                 Add a remote node (HOST=<ip>)"
        echo "  status               Check all fleet nodes"
        echo "  test                 Run a test task on each node"
        echo "  copy                 SCP fleet config to a remote node (HOST=<ip>)"
        exit 1
        ;;
esac
