#!/usr/bin/env bash
# =============================================================================
# AICP Fleet Management — initialize, join, status, and test fleet connectivity
#
# Usage:
#   make fleet-init                        Generate fleet token + config for this node
#   make fleet-join HOST=192.168.40.250    Add a remote node to the fleet
#   make fleet-status                      Check all fleet nodes
#   make fleet-test                        Run a task on each node to verify
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VENV_PYTHON="$REPO_ROOT/.venv/bin/python"
FLEET_CONFIG="$REPO_ROOT/config/fleet.yaml"
DEFAULT_PORT=9100

# ── Colors ────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
    RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
    CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; YELLOW=''; GREEN=''; CYAN=''; BOLD=''; RESET=''
fi

log_ok()   { echo -e "${GREEN}[OK]${RESET}    $*"; }
log_fail() { echo -e "${RED}[FAIL]${RESET}  $*" >&2; }
log_info() { echo -e "        $*"; }
log_step() { echo -e "${CYAN}[STEP]${RESET}  $*"; }
log_head() { echo -e "\n${BOLD}── $* ──${RESET}"; }
die()      { log_fail "$*"; exit 1; }

# ── Detect this machine's LAN IP ─────────────────────────────────────────────
detect_local_ip() {
    # Try to find the 192.168.x.x or 10.x.x.x IP (not WSL internal, not loopback)
    local ip
    # Method 1: ip route (most reliable on Linux)
    ip=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+' | head -1)
    if [[ -n "$ip" && "$ip" != 172.17.* && "$ip" != 127.* ]]; then
        echo "$ip"
        return
    fi
    # Method 2: hostname -I, pick first non-WSL IP
    for candidate in $(hostname -I 2>/dev/null); do
        case "$candidate" in
            192.168.*|10.*) echo "$candidate"; return ;;
        esac
    done
    # Method 3: WSL — check Windows host IP (the WSL host is the gateway)
    if grep -qi microsoft /proc/version 2>/dev/null; then
        local gateway
        gateway=$(ip route show default 2>/dev/null | awk '{print $3}' | head -1)
        if [[ -n "$gateway" ]]; then
            # The Windows host IP on the LAN — query via powershell
            local win_ip
            win_ip=$(powershell.exe -NoProfile -Command \
                "Get-NetIPAddress -AddressFamily IPv4 | Where-Object { \$_.IPAddress -like '192.168.*' -or \$_.IPAddress -like '10.*' } | Select-Object -First 1 -ExpandProperty IPAddress" \
                2>/dev/null | tr -d '\r')
            if [[ -n "$win_ip" ]]; then
                echo "$win_ip"
                return
            fi
        fi
    fi
    # Fallback
    hostname -I 2>/dev/null | awk '{print $1}'
}

# ── Generate a secure fleet token ─────────────────────────────────────────────
generate_token() {
    python3 -c "import secrets; print(secrets.token_urlsafe(32))"
}

# =============================================================================
# COMMAND: init
# =============================================================================
cmd_init() {
    log_head "Fleet initialization"

    local MY_IP
    MY_IP=$(detect_local_ip)
    local MY_NAME
    MY_NAME=$(hostname | tr '[:upper:]' '[:lower:]')

    if [[ -f "$FLEET_CONFIG" ]]; then
        log_info "Existing fleet config found at $FLEET_CONFIG"
        echo -n "Overwrite? [y/N] "
        read -r answer
        [[ "$answer" =~ ^[Yy] ]] || { log_info "Keeping existing config."; exit 0; }
    fi

    local TOKEN
    TOKEN=$(generate_token)

    log_step "Generating fleet config"
    log_info "This node:  $MY_NAME @ $MY_IP:$DEFAULT_PORT"
    log_info "Fleet token generated (shared secret for all nodes)"

    cat > "$FLEET_CONFIG" <<EOF
# AICP Fleet Configuration
# Generated by: make fleet-init
# Copy this file to each machine in config/fleet.yaml
# The token must be identical on all nodes.

fleet:
  token: "$TOKEN"
  port: $DEFAULT_PORT
  nodes:
    - name: "$MY_NAME"
      host: "$MY_IP"
      port: $DEFAULT_PORT
      role: primary
EOF

    log_ok "Fleet config written to $FLEET_CONFIG"

    # Also update default.yaml cluster section
    log_step "Updating config/default.yaml with cluster reference"
    "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

default_cfg_path = Path("config/default.yaml")
cfg = yaml.safe_load(default_cfg_path.read_text())

# Add/update cluster section pointing to fleet.yaml
cfg["cluster"] = {
    "config_file": "config/fleet.yaml",
    "auto_route": False,
}

default_cfg_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    log_ok "config/default.yaml updated with cluster reference"

    # Update .env with agent token
    if grep -q '^AICP_AGENT_SECRET=' .env 2>/dev/null; then
        sed -i "s|^AICP_AGENT_SECRET=.*|AICP_AGENT_SECRET=$TOKEN|" .env
    else
        echo "" >> .env
        echo "# ── Fleet (auto-generated by make fleet-init) ─────────────────────────────" >> .env
        echo "AICP_AGENT_SECRET=$TOKEN" >> .env
    fi
    log_ok "Agent token written to .env"

    echo ""
    echo -e "${BOLD}Next steps:${RESET}"
    echo ""
    echo "  1. Open firewall ports on BOTH machines:"
    echo "     make fleet-firewall    (shows rules for Windows Firewall / ESET / Linux)"
    echo ""
    echo "  2. Start the agent daemon on this machine:"
    echo "     make agent-up"
    echo "     (or: make install-service  for auto-start on boot)"
    echo ""
    echo "  3. Add the other machine:"
    echo "     make fleet-join HOST=<ip>"
    echo ""
    echo "  4. On the other machine:"
    echo "     - Copy config/fleet.yaml to their config/fleet.yaml"
    echo "     - Run: make agent-up"
    echo ""
    echo "  5. Verify:"
    echo "     make fleet-status"
    echo ""
}

# =============================================================================
# COMMAND: join — add a remote node
# =============================================================================
cmd_join() {
    local REMOTE_HOST="${1:-}"
    local REMOTE_PORT="${2:-$DEFAULT_PORT}"
    local REMOTE_NAME="${3:-}"

    [[ -n "$REMOTE_HOST" ]] || die "Usage: make fleet-join HOST=<ip> [PORT=<port>] [NAME=<name>]"
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    if [[ -z "$REMOTE_NAME" ]]; then
        # Try reverse DNS to resolve the actual hostname
        local resolved_name=""
        resolved_name=$(getent hosts "$REMOTE_HOST" 2>/dev/null | awk '{print $2}' | head -1)
        if [[ -n "$resolved_name" && "$resolved_name" != "$REMOTE_HOST" ]]; then
            # Strip domain if present (e.g., "node.local" → "node")
            REMOTE_NAME="${resolved_name%%.*}"
            REMOTE_NAME=$(echo "$REMOTE_NAME" | tr '[:upper:]' '[:lower:]')
        else
            # Try nslookup as fallback
            resolved_name=$(nslookup "$REMOTE_HOST" 2>/dev/null | grep 'name =' | awk '{print $NF}' | sed 's/\.$//' | head -1)
            if [[ -n "$resolved_name" ]]; then
                REMOTE_NAME="${resolved_name%%.*}"
                REMOTE_NAME=$(echo "$REMOTE_NAME" | tr '[:upper:]' '[:lower:]')
            else
                REMOTE_NAME="node-${REMOTE_HOST##*.}"
            fi
        fi
        log_info "Resolved name: $REMOTE_NAME (from $REMOTE_HOST)"
    fi

    log_head "Adding node to fleet"
    log_step "Checking connectivity to $REMOTE_HOST:$REMOTE_PORT"

    # Test basic connectivity
    if ! ping -c1 -W2 "$REMOTE_HOST" >/dev/null 2>&1; then
        log_fail "Cannot ping $REMOTE_HOST"
        log_info "Check that the machine is on and reachable on the network."
        exit 1
    fi
    log_ok "Host reachable (ping OK)"

    # Test if agent is running (3s timeout — it's OK if it's not up yet)
    local AGENT_OK=0
    if curl -sf --connect-timeout 3 --max-time 5 "http://$REMOTE_HOST:$REMOTE_PORT/health" >/dev/null 2>&1; then
        AGENT_OK=1
        log_ok "Agent daemon responding at $REMOTE_HOST:$REMOTE_PORT"
    else
        log_info "Agent not responding at $REMOTE_HOST:$REMOTE_PORT (that's OK — start it after setup)"
    fi

    # Test if LocalAI is running
    if curl -sf --connect-timeout 3 --max-time 5 "http://$REMOTE_HOST:8090/v1/models" >/dev/null 2>&1; then
        log_ok "LocalAI responding at $REMOTE_HOST:8090"
    else
        log_info "LocalAI not responding at $REMOTE_HOST:8090 (start it after setup)"
    fi

    # Check if node already exists
    if grep -q "host: \"$REMOTE_HOST\"" "$FLEET_CONFIG" 2>/dev/null || \
       grep -q "host: $REMOTE_HOST" "$FLEET_CONFIG" 2>/dev/null; then
        log_info "Node $REMOTE_HOST already in fleet config — updating"
        # Remove existing entry and re-add
        "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

fleet_path = Path("$FLEET_CONFIG")
cfg = yaml.safe_load(fleet_path.read_text())

# Remove existing node with same host
cfg["fleet"]["nodes"] = [
    n for n in cfg["fleet"].get("nodes", [])
    if n.get("host") != "$REMOTE_HOST"
]

# Add updated entry
cfg["fleet"]["nodes"].append({
    "name": "$REMOTE_NAME",
    "host": "$REMOTE_HOST",
    "port": $REMOTE_PORT,
    "role": "worker",
})

fleet_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    else
        # Append new node
        "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

fleet_path = Path("$FLEET_CONFIG")
cfg = yaml.safe_load(fleet_path.read_text())

cfg["fleet"]["nodes"].append({
    "name": "$REMOTE_NAME",
    "host": "$REMOTE_HOST",
    "port": $REMOTE_PORT,
    "role": "worker",
})

fleet_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    fi
    log_ok "Node $REMOTE_NAME ($REMOTE_HOST:$REMOTE_PORT) added to fleet config"

    # Show the fleet config
    echo ""
    echo -e "${BOLD}Fleet config ($FLEET_CONFIG):${RESET}"
    cat "$FLEET_CONFIG"

    echo ""
    echo -e "${BOLD}Next steps for the remote machine ($REMOTE_HOST):${RESET}"
    echo ""
    echo "  1. Copy the fleet config:"
    echo "     scp config/fleet.yaml $REMOTE_HOST:~/devops-expert-local-ai/config/fleet.yaml"
    echo ""
    echo "  2. Copy the agent token to their .env:"
    FLEET_TOKEN=$(grep 'token:' "$FLEET_CONFIG" | head -1 | awk '{print $2}' | tr -d '"')
    echo "     ssh $REMOTE_HOST 'echo AICP_AGENT_SECRET=$FLEET_TOKEN >> ~/devops-expert-local-ai/.env'"
    echo ""
    echo "  3. Start the agent on the remote machine:"
    echo "     ssh $REMOTE_HOST 'cd ~/devops-expert-local-ai && make agent-up'"
    echo ""
    echo "  4. Verify fleet:"
    echo "     make fleet-status"
    echo ""
}

# =============================================================================
# COMMAND: status — check all nodes
# =============================================================================
cmd_status() {
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    log_head "Fleet status (diagnostic)"

    "$VENV_PYTHON" - <<'PYEOF'
import os
import socket
import subprocess
import yaml
import sys
sys.path.insert(0, ".")

from pathlib import Path
import httpx
from aicp.agent.client import AgentClient

fleet_path = Path("config/fleet.yaml")
cfg = yaml.safe_load(fleet_path.read_text())
fleet = cfg.get("fleet", {})
token = fleet.get("token", "")
nodes = fleet.get("nodes", [])

if not nodes:
    print("  No nodes configured. Run: make fleet-join HOST=<ip>")
    sys.exit(0)

# Detect if we're in WSL
is_wsl = "microsoft" in open("/proc/version").read().lower() if os.path.exists("/proc/version") else False

print(f"  Fleet: {len(nodes)} node(s)")
if is_wsl:
    print(f"  Environment: WSL2 (port forwarding may be needed for agent)")
print()

for node in nodes:
    name = node["name"]
    host = node["host"]
    port = node.get("port", 9100)
    role = node.get("role", "worker")

    print(f"  {name} ({host}:{port}) [{role}]")

    # ── Step 1: DNS/hostname resolution ──
    try:
        resolved = socket.getaddrinfo(host, None, socket.AF_INET)[0][4][0]
        if resolved != host:
            print(f"    Hostname: {host} → {resolved}")
    except socket.gaierror:
        print(f"    \033[0;31m✗ DNS:\033[0m Cannot resolve hostname '{host}'")
        print()
        continue

    # ── Step 2: Ping ──
    ping_ok = False
    try:
        r = subprocess.run(["ping", "-c1", "-W2", host], capture_output=True, timeout=5)
        ping_ok = r.returncode == 0
    except Exception:
        pass
    if ping_ok:
        print(f"    \033[0;32m✓ Ping:\033[0m reachable")
    else:
        print(f"    \033[0;31m✗ Ping:\033[0m unreachable — check network/firewall")
        print()
        continue

    # ── Step 3: TCP port check (is anything listening?) ──
    agent_port_open = False
    try:
        s = socket.create_connection((host, port), timeout=3)
        s.close()
        agent_port_open = True
    except (ConnectionRefusedError, OSError, socket.timeout):
        pass

    if not agent_port_open:
        print(f"    \033[0;31m✗ TCP {port}:\033[0m port not reachable")
        print(f"      ℹ Firewall? Run: make fleet-firewall")
        # Diagnose further
        if is_wsl and host not in ("127.0.0.1", "localhost"):
            # Check if this is our own node
            local_ips = []
            try:
                out = subprocess.check_output(["hostname", "-I"], text=True).strip().split()
                local_ips = out
            except Exception:
                pass
            # Check if this host is the local machine's LAN IP (WSL port forward needed)
            try:
                wsl_forward = subprocess.check_output(
                    ["powershell.exe", "-NoProfile", "-Command",
                     "netsh interface portproxy show v4tov4"],
                    text=True, timeout=5,
                ).replace("\r", "")
            except Exception:
                wsl_forward = ""
            if str(port) in wsl_forward:
                print(f"      ℹ Port forward exists but agent may not be running")
            else:
                print(f"      ℹ WSL detected — this port also needs forwarding:")
                print(f"        Run: make wsl-forward")
    else:
        print(f"    \033[0;32m✓ TCP {port}:\033[0m port open")

    # ── Step 4: Agent HTTP health ──
    agent_ok = False
    agent_err = ""
    client = AgentClient(host, port, token)
    try:
        r = httpx.get(f"http://{host}:{port}/health", timeout=3.0)
        if r.status_code == 200:
            agent_ok = True
        elif r.status_code == 401:
            agent_err = "401 Unauthorized — token mismatch"
        else:
            agent_err = f"HTTP {r.status_code}"
    except httpx.ConnectError as e:
        agent_err = f"connection refused"
    except httpx.TimeoutException:
        agent_err = f"timeout"
    except Exception as e:
        agent_err = str(e)[:80]

    if agent_ok:
        print(f"    \033[0;32m✓ Agent:\033[0m online")
    else:
        reason = f" — {agent_err}" if agent_err else ""
        print(f"    \033[0;31m✗ Agent:\033[0m offline{reason}")
        if "refused" in agent_err:
            print(f"      ℹ Agent daemon not running. On that machine run: make agent-up")

    # ── Step 5: LocalAI ──
    localai_ok = False
    localai_err = ""
    models = []
    try:
        r = httpx.get(f"http://{host}:8090/v1/models", timeout=3.0)
        if r.status_code == 200:
            localai_ok = True
            models = [m["id"] for m in r.json().get("data", [])]
        else:
            localai_err = f"HTTP {r.status_code}"
    except httpx.ConnectError:
        localai_err = "connection refused"
    except httpx.TimeoutException:
        localai_err = "timeout"
    except Exception as e:
        localai_err = str(e)[:80]

    if localai_ok:
        print(f"    \033[0;32m✓ LocalAI:\033[0m online  models: {', '.join(models)}")
    else:
        reason = f" — {localai_err}" if localai_err else ""
        print(f"    \033[0;31m✗ LocalAI:\033[0m offline{reason}")
        if "refused" in localai_err:
            print(f"      ℹ LocalAI not running. On that machine run: make local-up")

    # ── Step 6: GPU info (only if agent is up) ──
    if agent_ok:
        try:
            status = client.status()
            if status and status.get("gpus"):
                for g in status["gpus"]:
                    gname = g.get("name", "?")
                    free = g.get("vram_free_mb", "?")
                    total = g.get("vram_total_mb", "?")
                    print(f"    GPU:     {gname} ({free}MB free / {total}MB)")
            if status and status.get("models"):
                names = [m.get("name", "?") for m in status["models"]]
                print(f"    Models:  {', '.join(names)}")
        except Exception:
            pass

    print()

# ── Summary ──
online_count = 0
for node in nodes:
    host = node["host"]
    port = node.get("port", 9100)
    try:
        r = httpx.get(f"http://{host}:{port}/health", timeout=2.0)
        if r.status_code == 200:
            online_count += 1
    except Exception:
        pass

print(f"  Summary: {online_count}/{len(nodes)} agents online")
if online_count < len(nodes):
    print(f"  Run 'make agent-up' on offline machines, then 'make fleet-status' again.")

PYEOF
}

# =============================================================================
# COMMAND: test — run a task on each node
# =============================================================================
cmd_test() {
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    log_head "Fleet connectivity test"

    "$VENV_PYTHON" - <<'PYEOF'
import yaml
import json
import time
import sys
sys.path.insert(0, ".")

from pathlib import Path
from aicp.agent.client import AgentClient

fleet_path = Path("config/fleet.yaml")
cfg = yaml.safe_load(fleet_path.read_text())
fleet = cfg.get("fleet", {})
token = fleet.get("token", "")
nodes = fleet.get("nodes", [])

for node in nodes:
    name = node["name"]
    host = node["host"]
    port = node.get("port", 9100)

    print(f"  Testing {name} ({host}:{port})...")
    client = AgentClient(host, port, token)

    if not client.health():
        print(f"    \033[0;31m✗ Agent not responding\033[0m")
        continue

    try:
        start = time.time()
        result = client.execute_task(
            prompt="Reply with exactly: FLEET_TEST_OK",
            mode="think",
            backend="local",
        )
        elapsed = time.time() - start
        text = result.get("result", "")
        if "FLEET_TEST_OK" in text or len(text) > 0:
            print(f"    \033[0;32m✓ Task executed in {elapsed:.1f}s\033[0m")
            print(f"    Response: {text[:100]}")
        else:
            print(f"    \033[0;33m⚠ Got empty response\033[0m")
    except Exception as e:
        print(f"    \033[0;31m✗ Task failed: {e}\033[0m")

    print()

PYEOF
}

# =============================================================================
# COMMAND: copy-config — helper to scp fleet.yaml to a remote node
# =============================================================================
cmd_copy() {
    local REMOTE_HOST="${1:-}"
    [[ -n "$REMOTE_HOST" ]] || die "Usage: make fleet-copy HOST=<ip>"
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    FLEET_TOKEN=$(grep 'token:' "$FLEET_CONFIG" | head -1 | awk '{print $2}' | tr -d '"')

    log_head "Copying fleet config to $REMOTE_HOST"

    log_step "Copying config/fleet.yaml"
    scp "$FLEET_CONFIG" "$REMOTE_HOST:~/devops-expert-local-ai/config/fleet.yaml"
    log_ok "fleet.yaml copied"

    log_step "Setting agent token in remote .env"
    ssh "$REMOTE_HOST" "cd ~/devops-expert-local-ai && \
        grep -q '^AICP_AGENT_SECRET=' .env 2>/dev/null && \
        sed -i 's|^AICP_AGENT_SECRET=.*|AICP_AGENT_SECRET=$FLEET_TOKEN|' .env || \
        echo 'AICP_AGENT_SECRET=$FLEET_TOKEN' >> .env"
    log_ok "Agent token set on remote"

    echo ""
    echo -e "${BOLD}Done. Now start the agent on $REMOTE_HOST:${RESET}"
    echo "  ssh $REMOTE_HOST 'cd ~/devops-expert-local-ai && make agent-up'"
    echo ""
}

# =============================================================================
# COMMAND: firewall — print firewall rules for all AICP ports
# =============================================================================
cmd_firewall() {
    log_head "AICP Firewall Rules"

    echo ""
    echo -e "${BOLD}Ports used by AICP:${RESET}"
    echo ""
    echo "  Port   Service           Protocol  Notes"
    echo "  ─────  ────────────────  ────────  ─────────────────────────────────────"
    echo "  8090   LocalAI API       TCP/HTTP  Model inference (chat, embed, TTS, etc.)"
    echo "  9100   AICP Agent        TCP/HTTP  Fleet communication between nodes"
    echo ""
    echo "  Both ports need to be open for INBOUND TCP on every fleet machine."
    echo ""

    # Detect environment
    local is_wsl=0
    grep -qi microsoft /proc/version 2>/dev/null && is_wsl=1

    echo -e "${BOLD}═══ Option A: Windows Firewall (built-in) ═══${RESET}"
    echo ""
    echo "  Run these in an ${BOLD}Administrator PowerShell${RESET}:"
    echo ""
    echo "  # Allow LocalAI API (port 8090)"
    echo "  New-NetFirewallRule -DisplayName 'AICP - LocalAI API' \\"
    echo "    -Direction Inbound -Protocol TCP -LocalPort 8090 \\"
    echo "    -Action Allow -Profile Private"
    echo ""
    echo "  # Allow AICP Agent (port 9100)"
    echo "  New-NetFirewallRule -DisplayName 'AICP - Agent Daemon' \\"
    echo "    -Direction Inbound -Protocol TCP -LocalPort 9100 \\"
    echo "    -Action Allow -Profile Private"
    echo ""
    echo "  To verify:"
    echo "  Get-NetFirewallRule -DisplayName 'AICP*' | Format-Table DisplayName,Enabled,Direction"
    echo ""
    echo "  To remove later:"
    echo "  Remove-NetFirewallRule -DisplayName 'AICP - LocalAI API'"
    echo "  Remove-NetFirewallRule -DisplayName 'AICP - Agent Daemon'"
    echo ""

    echo -e "${BOLD}═══ Option B: ESET Firewall ═══${RESET}"
    echo ""
    echo "  If ESET Smart Security / Internet Security manages your firewall,"
    echo "  Windows Firewall rules may be IGNORED. Configure in ESET instead:"
    echo ""
    echo "  1. Open ESET → Setup → Network protection → Firewall"
    echo "  2. Click 'Configure rules...' (or 'Interactive mode' rules)"
    echo "  3. Add TWO rules:"
    echo ""
    echo "     Rule 1: AICP - LocalAI API"
    echo "       Direction:   Inbound"
    echo "       Protocol:    TCP"
    echo "       Local port:  8090"
    echo "       Action:      Allow"
    echo "       Profile:     Home / Trusted network"
    echo ""
    echo "     Rule 2: AICP - Agent Daemon"
    echo "       Direction:   Inbound"
    echo "       Protocol:    TCP"
    echo "       Local port:  9100"
    echo "       Action:      Allow"
    echo "       Profile:     Home / Trusted network"
    echo ""
    echo "  Tip: If ESET is in Interactive mode, it will prompt when a"
    echo "  connection comes in — choose 'Allow' and 'Create rule'."
    echo ""
    echo "  To check if ESET is managing firewall (vs Windows):"
    echo "    ESET → Setup → Network protection → see if Firewall shows 'Active'"
    echo ""

    if [[ "$is_wsl" -eq 1 ]]; then
        echo -e "${BOLD}═══ WSL2 Note ═══${RESET}"
        echo ""
        echo "  Docker ports (8090) are auto-exposed to LAN by Windows."
        echo "  Agent port (9100) runs in WSL and needs port forwarding:"
        echo ""
        echo "    make wsl-forward          # Set up port forward for 9100"
        echo "    make wsl-forward-check    # Verify current forwards"
        echo ""
        echo "  Port forward + firewall rule are BOTH needed for 9100."
        echo ""
    fi

    echo -e "${BOLD}═══ Linux (bare metal, no WSL) ═══${RESET}"
    echo ""
    echo "  If running on native Linux, use iptables/ufw:"
    echo ""
    echo "  # ufw (Ubuntu/Debian)"
    echo "  sudo ufw allow 8090/tcp comment 'AICP - LocalAI API'"
    echo "  sudo ufw allow 9100/tcp comment 'AICP - Agent Daemon'"
    echo ""
    echo "  # iptables (any distro)"
    echo "  sudo iptables -A INPUT -p tcp --dport 8090 -j ACCEPT"
    echo "  sudo iptables -A INPUT -p tcp --dport 9100 -j ACCEPT"
    echo ""

    # Quick connectivity test hint
    echo -e "${BOLD}═══ Quick test from another machine ═══${RESET}"
    echo ""
    local MY_IP
    MY_IP=$(detect_local_ip)
    echo "  From the other machine, run:"
    echo "    curl -sf http://$MY_IP:8090/v1/models    # Should return JSON"
    echo "    curl -sf http://$MY_IP:9100/health        # Should return {\"status\":\"ok\"}"
    echo ""
}

# =============================================================================
# Dispatch
# =============================================================================
CMD="${1:-}"
shift || true

case "$CMD" in
    init)      cmd_init ;;
    join)      cmd_join "${HOST:-${1:-}}" "${PORT:-$DEFAULT_PORT}" "${FLEET_NAME:-}" ;;
    status)    cmd_status ;;
    test)      cmd_test ;;
    copy)      cmd_copy "${HOST:-$1}" ;;
    firewall)  cmd_firewall ;;
    *)
        echo "Usage: scripts/fleet.sh <command>"
        echo ""
        echo "Commands:"
        echo "  init                 Generate fleet token + config for this node"
        echo "  join                 Add a remote node (HOST=<ip>)"
        echo "  status               Check all fleet nodes"
        echo "  test                 Run a test task on each node"
        echo "  copy                 SCP fleet config to a remote node (HOST=<ip>)"
        echo "  firewall             Show firewall rules for all AICP ports"
        exit 1
        ;;
esac
