#!/usr/bin/env bash
# =============================================================================
# AICP Fleet Management — initialize, join, status, and test fleet connectivity
#
# Usage:
#   make fleet-init                        Generate fleet token + config for this node
#   make fleet-join HOST=192.168.40.250    Add a remote node to the fleet
#   make fleet-status                      Check all fleet nodes
#   make fleet-test                        Run a task on each node to verify
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VENV_PYTHON="$REPO_ROOT/.venv/bin/python"
FLEET_CONFIG="$REPO_ROOT/config/fleet.yaml"
DEFAULT_PORT=9100

# ── Colors ────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
    RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
    CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; YELLOW=''; GREEN=''; CYAN=''; BOLD=''; RESET=''
fi

log_ok()   { echo -e "${GREEN}[OK]${RESET}    $*"; }
log_fail() { echo -e "${RED}[FAIL]${RESET}  $*" >&2; }
log_info() { echo -e "        $*"; }
log_step() { echo -e "${CYAN}[STEP]${RESET}  $*"; }
log_head() { echo -e "\n${BOLD}── $* ──${RESET}"; }
die()      { log_fail "$*"; exit 1; }

# ── Detect this machine's LAN IP ─────────────────────────────────────────────
detect_local_ip() {
    # Try to find the 192.168.x.x or 10.x.x.x IP (not WSL internal, not loopback)
    local ip
    # Method 1: ip route (most reliable on Linux)
    ip=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+' | head -1)
    if [[ -n "$ip" && "$ip" != 172.17.* && "$ip" != 127.* ]]; then
        echo "$ip"
        return
    fi
    # Method 2: hostname -I, pick first non-WSL IP
    for candidate in $(hostname -I 2>/dev/null); do
        case "$candidate" in
            192.168.*|10.*) echo "$candidate"; return ;;
        esac
    done
    # Method 3: WSL — check Windows host IP (the WSL host is the gateway)
    if grep -qi microsoft /proc/version 2>/dev/null; then
        local gateway
        gateway=$(ip route show default 2>/dev/null | awk '{print $3}' | head -1)
        if [[ -n "$gateway" ]]; then
            # The Windows host IP on the LAN — query via powershell
            local win_ip
            win_ip=$(powershell.exe -NoProfile -Command \
                "Get-NetIPAddress -AddressFamily IPv4 | Where-Object { \$_.IPAddress -like '192.168.*' -or \$_.IPAddress -like '10.*' } | Select-Object -First 1 -ExpandProperty IPAddress" \
                2>/dev/null | tr -d '\r')
            if [[ -n "$win_ip" ]]; then
                echo "$win_ip"
                return
            fi
        fi
    fi
    # Fallback
    hostname -I 2>/dev/null | awk '{print $1}'
}

# ── Generate a secure fleet token ─────────────────────────────────────────────
generate_token() {
    python3 -c "import secrets; print(secrets.token_urlsafe(32))"
}

# =============================================================================
# COMMAND: init
# =============================================================================
cmd_init() {
    log_head "Fleet initialization"

    local MY_IP
    MY_IP=$(detect_local_ip)
    local MY_NAME
    MY_NAME=$(hostname | tr '[:upper:]' '[:lower:]')

    if [[ -f "$FLEET_CONFIG" ]]; then
        log_info "Existing fleet config found at $FLEET_CONFIG"
        echo -n "Overwrite? [y/N] "
        read -r answer
        [[ "$answer" =~ ^[Yy] ]] || { log_info "Keeping existing config."; exit 0; }
    fi

    local TOKEN
    TOKEN=$(generate_token)

    log_step "Generating fleet config"
    log_info "This node:  $MY_NAME @ $MY_IP:$DEFAULT_PORT"
    log_info "Fleet token generated (shared secret for all nodes)"

    cat > "$FLEET_CONFIG" <<EOF
# AICP Fleet Configuration
# Generated by: make fleet-init
# Copy this file to each machine in config/fleet.yaml
# The token must be identical on all nodes.

fleet:
  token: "$TOKEN"
  port: $DEFAULT_PORT
  nodes:
    - name: "$MY_NAME"
      host: "$MY_IP"
      port: $DEFAULT_PORT
      role: primary
EOF

    log_ok "Fleet config written to $FLEET_CONFIG"

    # Also update default.yaml cluster section
    log_step "Updating config/default.yaml with cluster reference"
    "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

default_cfg_path = Path("config/default.yaml")
cfg = yaml.safe_load(default_cfg_path.read_text())

# Add/update cluster section pointing to fleet.yaml
cfg["cluster"] = {
    "config_file": "config/fleet.yaml",
    "auto_route": False,
}

default_cfg_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    log_ok "config/default.yaml updated with cluster reference"

    # Update .env with agent token
    if grep -q '^AICP_AGENT_SECRET=' .env 2>/dev/null; then
        sed -i "s|^AICP_AGENT_SECRET=.*|AICP_AGENT_SECRET=$TOKEN|" .env
    else
        echo "" >> .env
        echo "# ── Fleet (auto-generated by make fleet-init) ─────────────────────────────" >> .env
        echo "AICP_AGENT_SECRET=$TOKEN" >> .env
    fi
    log_ok "Agent token written to .env"

    # Check for LocalAI P2P token
    # The P2P token is a structured base64 blob generated by LocalAI/EdgeVPN.
    # It cannot be a random string — it contains crypto keys, OTP config, etc.
    # The token is auto-generated when LocalAI starts with --p2p enabled.
    log_step "Checking LocalAI P2P token"
    if grep -q '^LOCALAI_P2P_TOKEN=' .env 2>/dev/null && \
       [[ -n "$(grep '^LOCALAI_P2P_TOKEN=' .env | cut -d= -f2-)" ]]; then
        log_ok "P2P token already in .env"
    else
        # Try to fetch from running LocalAI instance
        local P2P_TOKEN=""
        P2P_TOKEN=$(curl -sf http://localhost:${LOCALAI_PORT:-8090}/api/p2p/token 2>/dev/null || \
                     curl -sf http://localhost:${LOCALAI_PORT:-8090}/p2p/token 2>/dev/null || true)
        if [[ -n "$P2P_TOKEN" && ${#P2P_TOKEN} -gt 50 ]]; then
            if grep -q '^LOCALAI_P2P_TOKEN=' .env 2>/dev/null; then
                sed -i "s|^LOCALAI_P2P_TOKEN=.*|LOCALAI_P2P_TOKEN=$P2P_TOKEN|" .env
            else
                echo "" >> .env
                echo "# ── LocalAI P2P (fetched from running instance) ────────────────────────────" >> .env
                echo "LOCALAI_P2P_TOKEN=$P2P_TOKEN" >> .env
                echo "LOCALAI_P2P_NETWORK_ID=aicp-fleet" >> .env
            fi
            log_ok "P2P token fetched from LocalAI and saved to .env"
        else
            log_info "P2P token not available yet."
            log_info "It will be auto-generated when you start LocalAI in P2P mode:"
            log_info "  make local-down && make local-up-p2p"
            log_info "Then run: make p2p-token   to fetch and distribute it."
            # Write placeholder so the env var exists
            if ! grep -q '^LOCALAI_P2P_TOKEN=' .env 2>/dev/null; then
                echo "" >> .env
                echo "# ── LocalAI P2P (will be populated by make p2p-token) ──────────────────────" >> .env
                echo "LOCALAI_P2P_TOKEN=" >> .env
                echo "LOCALAI_P2P_NETWORK_ID=aicp-fleet" >> .env
            fi
        fi
    fi

    echo ""
    echo -e "${BOLD}Next steps:${RESET}"
    echo ""
    echo "  1. Open firewall ports on BOTH machines:"
    echo "     make fleet-firewall"
    echo ""
    echo "  2. Start LocalAI with P2P federation:"
    echo "     make local-down && make local-up-p2p"
    echo ""
    echo "  3. Fetch the P2P token (auto-generated by LocalAI on first P2P start):"
    echo "     make p2p-token"
    echo ""
    echo "  4. Start the agent daemon:"
    echo "     make agent-up"
    echo ""
    echo "  5. Register + configure the remote machine:"
    echo "     make fleet-join HOST=<ip>"
    echo "     make fleet-copy HOST=<ip>"
    echo ""
    echo "  6. On the remote machine:"
    echo "     make local-down && make local-up-p2p"
    echo "     make agent-up"
    echo ""
    echo "  7. Verify:"
    echo "     make fleet-status"
    echo "     make fleet-test"
    echo ""
}

# =============================================================================
# COMMAND: join — add a remote node
# =============================================================================
cmd_join() {
    local REMOTE_HOST="${1:-}"
    local REMOTE_PORT="${2:-$DEFAULT_PORT}"
    local REMOTE_NAME="${3:-}"

    [[ -n "$REMOTE_HOST" ]] || die "Usage: make fleet-join HOST=<ip> [PORT=<port>] [NAME=<name>]"
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    if [[ -z "$REMOTE_NAME" ]]; then
        local resolved_name=""

        # Method 1: reverse DNS (works on networks with proper DNS)
        resolved_name=$(getent hosts "$REMOTE_HOST" 2>/dev/null | awk '{print $2}' | head -1)

        # Method 2: NetBIOS via PowerShell (works on Windows home LANs)
        if [[ -z "$resolved_name" || "$resolved_name" == "$REMOTE_HOST" ]]; then
            if command -v powershell.exe >/dev/null 2>&1; then
                resolved_name=$(powershell.exe -NoProfile -Command \
                    "try { ([System.Net.Dns]::GetHostEntry('$REMOTE_HOST')).HostName } catch { '' }" \
                    2>/dev/null | tr -d '\r\n')
            fi
        fi

        # Method 3: nslookup reverse lookup
        if [[ -z "$resolved_name" || "$resolved_name" == "$REMOTE_HOST" ]]; then
            resolved_name=$(nslookup "$REMOTE_HOST" 2>/dev/null | grep 'name =' | awk '{print $NF}' | sed 's/\.$//' | head -1)
        fi

        # Method 4: ping -a (some systems resolve via NetBIOS/mDNS)
        if [[ -z "$resolved_name" || "$resolved_name" == "$REMOTE_HOST" ]]; then
            resolved_name=$(ping -c1 -W2 -a "$REMOTE_HOST" 2>/dev/null | head -1 | grep -oP 'PING \K[^ (]+' | head -1)
            # Only use if it's not just the IP repeated
            [[ "$resolved_name" == "$REMOTE_HOST" ]] && resolved_name=""
        fi

        if [[ -n "$resolved_name" && "$resolved_name" != "$REMOTE_HOST" ]]; then
            # Strip domain if present (e.g., "NODE-250.local" → "node-250")
            REMOTE_NAME="${resolved_name%%.*}"
            REMOTE_NAME=$(echo "$REMOTE_NAME" | tr '[:upper:]' '[:lower:]')
            log_ok "Resolved hostname: $REMOTE_NAME (from $REMOTE_HOST)"
        else
            REMOTE_NAME="node-${REMOTE_HOST##*.}"
            log_info "Could not resolve hostname for $REMOTE_HOST — using '$REMOTE_NAME'"
            log_info "Override with: make fleet-join HOST=$REMOTE_HOST FLEET_NAME=<name>"
        fi
    fi

    log_head "Adding node to fleet"
    log_step "Checking connectivity to $REMOTE_HOST:$REMOTE_PORT"

    # Test basic connectivity
    if ! ping -c1 -W2 "$REMOTE_HOST" >/dev/null 2>&1; then
        log_fail "Cannot ping $REMOTE_HOST"
        log_info "Check that the machine is on and reachable on the network."
        exit 1
    fi
    log_ok "Host reachable (ping OK)"

    # Test if agent is running (3s timeout — it's OK if it's not up yet)
    local AGENT_OK=0
    if curl -sf --connect-timeout 3 --max-time 5 "http://$REMOTE_HOST:$REMOTE_PORT/health" >/dev/null 2>&1; then
        AGENT_OK=1
        log_ok "Agent daemon responding at $REMOTE_HOST:$REMOTE_PORT"
    else
        log_info "Agent not responding at $REMOTE_HOST:$REMOTE_PORT (that's OK — start it after setup)"
    fi

    # Test if LocalAI is running
    if curl -sf --connect-timeout 3 --max-time 5 "http://$REMOTE_HOST:8090/v1/models" >/dev/null 2>&1; then
        log_ok "LocalAI responding at $REMOTE_HOST:8090"
    else
        log_info "LocalAI not responding at $REMOTE_HOST:8090 (start it after setup)"
    fi

    # Check if node already exists
    if grep -q "host: \"$REMOTE_HOST\"" "$FLEET_CONFIG" 2>/dev/null || \
       grep -q "host: $REMOTE_HOST" "$FLEET_CONFIG" 2>/dev/null; then
        log_info "Node $REMOTE_HOST already in fleet config — updating"
        # Remove existing entry and re-add
        "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

fleet_path = Path("$FLEET_CONFIG")
cfg = yaml.safe_load(fleet_path.read_text())

# Remove existing node with same host
cfg["fleet"]["nodes"] = [
    n for n in cfg["fleet"].get("nodes", [])
    if n.get("host") != "$REMOTE_HOST"
]

# Add updated entry
cfg["fleet"]["nodes"].append({
    "name": "$REMOTE_NAME",
    "host": "$REMOTE_HOST",
    "port": $REMOTE_PORT,
    "role": "worker",
})

fleet_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    else
        # Append new node
        "$VENV_PYTHON" - <<PYEOF
import yaml
from pathlib import Path

fleet_path = Path("$FLEET_CONFIG")
cfg = yaml.safe_load(fleet_path.read_text())

cfg["fleet"]["nodes"].append({
    "name": "$REMOTE_NAME",
    "host": "$REMOTE_HOST",
    "port": $REMOTE_PORT,
    "role": "worker",
})

fleet_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
PYEOF
    fi
    log_ok "Node $REMOTE_NAME ($REMOTE_HOST:$REMOTE_PORT) added to fleet config"

    # Show the fleet config
    echo ""
    echo -e "${BOLD}Fleet config ($FLEET_CONFIG):${RESET}"
    cat "$FLEET_CONFIG"

    echo ""
    echo -e "${BOLD}Next steps:${RESET}"
    echo ""
    echo "  1. Push config + tokens to the remote machine:"
    echo "     make fleet-copy HOST=$REMOTE_HOST"
    echo ""
    echo "  2. On the remote machine ($REMOTE_HOST):"
    echo "     cd ~/devops-expert-local-ai"
    echo "     make local-down && make local-up-p2p"
    echo "     make agent-up"
    echo ""
    echo "  3. Verify:"
    echo "     make fleet-status"
    echo ""
}

# =============================================================================
# COMMAND: status — check all nodes
# =============================================================================
cmd_status() {
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    log_head "Fleet status (diagnostic)"

    "$VENV_PYTHON" - <<'PYEOF'
import os
import socket
import subprocess
import yaml
import sys
sys.path.insert(0, ".")

from pathlib import Path
import httpx
from aicp.agent.client import AgentClient

fleet_path = Path("config/fleet.yaml")
cfg = yaml.safe_load(fleet_path.read_text())
fleet = cfg.get("fleet", {})
token = fleet.get("token", "")
nodes = fleet.get("nodes", [])

if not nodes:
    print("  No nodes configured. Run: make fleet-join HOST=<ip>")
    sys.exit(0)

# Detect if we're in WSL
is_wsl = "microsoft" in open("/proc/version").read().lower() if os.path.exists("/proc/version") else False

print(f"  Fleet: {len(nodes)} node(s)")
if is_wsl:
    print(f"  Environment: WSL2 (port forwarding may be needed for agent)")
print()

for node in nodes:
    name = node["name"]
    host = node["host"]
    port = node.get("port", 9100)
    role = node.get("role", "worker")

    print(f"  {name} ({host}:{port}) [{role}]")

    # ── Step 1: DNS/hostname resolution ──
    try:
        resolved = socket.getaddrinfo(host, None, socket.AF_INET)[0][4][0]
        if resolved != host:
            print(f"    Hostname: {host} → {resolved}")
    except socket.gaierror:
        print(f"    \033[0;31m✗ DNS:\033[0m Cannot resolve hostname '{host}'")
        print()
        continue

    # ── Step 2: Ping ──
    ping_ok = False
    try:
        r = subprocess.run(["ping", "-c1", "-W2", host], capture_output=True, timeout=5)
        ping_ok = r.returncode == 0
    except Exception:
        pass
    if ping_ok:
        print(f"    \033[0;32m✓ Ping:\033[0m reachable")
    else:
        print(f"    \033[0;31m✗ Ping:\033[0m unreachable — check network/firewall")
        print()
        continue

    # ── Step 3: TCP port check (is anything listening?) ──
    agent_port_open = False
    try:
        s = socket.create_connection((host, port), timeout=3)
        s.close()
        agent_port_open = True
    except (ConnectionRefusedError, OSError, socket.timeout):
        pass

    if not agent_port_open:
        print(f"    \033[0;31m✗ TCP {port}:\033[0m port not reachable")
        print(f"      ℹ Firewall? Run: make fleet-firewall")
        # Diagnose further
        if is_wsl and host not in ("127.0.0.1", "localhost"):
            # Check if this is our own node
            local_ips = []
            try:
                out = subprocess.check_output(["hostname", "-I"], text=True).strip().split()
                local_ips = out
            except Exception:
                pass
            # Check if this host is the local machine's LAN IP (WSL port forward needed)
            try:
                wsl_forward = subprocess.check_output(
                    ["powershell.exe", "-NoProfile", "-Command",
                     "netsh interface portproxy show v4tov4"],
                    text=True, timeout=5,
                ).replace("\r", "")
            except Exception:
                wsl_forward = ""
            if str(port) in wsl_forward:
                print(f"      ℹ Port forward exists but agent may not be running")
            else:
                print(f"      ℹ WSL detected — this port also needs forwarding:")
                print(f"        Run: make wsl-forward")
    else:
        print(f"    \033[0;32m✓ TCP {port}:\033[0m port open")

    # ── Step 4: Agent HTTP health ──
    agent_ok = False
    agent_err = ""
    client = AgentClient(host, port, token)
    try:
        r = httpx.get(f"http://{host}:{port}/health", timeout=3.0)
        if r.status_code == 200:
            agent_ok = True
        elif r.status_code == 401:
            agent_err = "401 Unauthorized — token mismatch"
        else:
            agent_err = f"HTTP {r.status_code}"
    except httpx.ConnectError as e:
        agent_err = f"connection refused"
    except httpx.TimeoutException:
        agent_err = f"timeout"
    except Exception as e:
        agent_err = str(e)[:80]

    if agent_ok:
        print(f"    \033[0;32m✓ Agent:\033[0m online")
    else:
        reason = f" — {agent_err}" if agent_err else ""
        print(f"    \033[0;31m✗ Agent:\033[0m offline{reason}")
        if "refused" in agent_err:
            print(f"      ℹ Agent daemon not running. On that machine run: make agent-up")

    # ── Step 5: LocalAI ──
    localai_ok = False
    localai_err = ""
    models = []
    try:
        r = httpx.get(f"http://{host}:8090/v1/models", timeout=3.0)
        if r.status_code == 200:
            localai_ok = True
            models = [m["id"] for m in r.json().get("data", [])]
        else:
            localai_err = f"HTTP {r.status_code}"
    except httpx.ConnectError:
        localai_err = "connection refused"
    except httpx.TimeoutException:
        localai_err = "timeout"
    except Exception as e:
        localai_err = str(e)[:80]

    if localai_ok:
        print(f"    \033[0;32m✓ LocalAI:\033[0m online  models: {', '.join(models)}")
    else:
        reason = f" — {localai_err}" if localai_err else ""
        print(f"    \033[0;31m✗ LocalAI:\033[0m offline{reason}")
        if "refused" in localai_err:
            print(f"      ℹ LocalAI not running. On that machine run: make local-up")

    # ── Step 6: P2P port check ──
    p2p_port = 9876
    p2p_open = False
    try:
        s = socket.create_connection((host, p2p_port), timeout=3)
        s.close()
        p2p_open = True
    except (ConnectionRefusedError, OSError, socket.timeout):
        pass

    if p2p_open:
        print(f"    \033[0;32m✓ P2P {p2p_port}:\033[0m port open (libp2p)")
    elif localai_ok:
        print(f"    \033[1;33m⚠ P2P {p2p_port}:\033[0m not reachable (LocalAI may not be in P2P mode)")
        print(f"      ℹ Start with: make local-down && make local-up-p2p")
    # If LocalAI itself is down, no point mentioning P2P

    # ── Step 7: GPU info (only if agent is up) ──
    if agent_ok:
        try:
            status = client.status()
            if status and status.get("gpus"):
                for g in status["gpus"]:
                    gname = g.get("name", "?")
                    free = g.get("vram_free_mb", "?")
                    total = g.get("vram_total_mb", "?")
                    print(f"    GPU:     {gname} ({free}MB free / {total}MB)")
            if status and status.get("models"):
                names = [m.get("name", "?") for m in status["models"]]
                print(f"    Models:  {', '.join(names)}")
        except Exception:
            pass

    print()

# ── Summary ──
online_count = 0
for node in nodes:
    host = node["host"]
    port = node.get("port", 9100)
    try:
        r = httpx.get(f"http://{host}:{port}/health", timeout=2.0)
        if r.status_code == 200:
            online_count += 1
    except Exception:
        pass

print(f"  Summary: {online_count}/{len(nodes)} agents online")
if online_count < len(nodes):
    print(f"  Run 'make agent-up' on offline machines, then 'make fleet-status' again.")

PYEOF
}

# =============================================================================
# COMMAND: test — run a task on each node
# =============================================================================
cmd_test() {
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    log_head "Fleet connectivity test"

    "$VENV_PYTHON" - <<'PYEOF'
import yaml
import json
import time
import sys
sys.path.insert(0, ".")

from pathlib import Path
from aicp.agent.client import AgentClient

fleet_path = Path("config/fleet.yaml")
cfg = yaml.safe_load(fleet_path.read_text())
fleet = cfg.get("fleet", {})
token = fleet.get("token", "")
nodes = fleet.get("nodes", [])

for node in nodes:
    name = node["name"]
    host = node["host"]
    port = node.get("port", 9100)

    print(f"  Testing {name} ({host}:{port})...")
    client = AgentClient(host, port, token)

    if not client.health():
        print(f"    \033[0;31m✗ Agent not responding\033[0m")
        continue

    try:
        start = time.time()
        result = client.execute_task(
            prompt="Reply with exactly: FLEET_TEST_OK",
            mode="think",
            backend="local",
        )
        elapsed = time.time() - start
        text = result.get("result", "")
        if "FLEET_TEST_OK" in text or len(text) > 0:
            print(f"    \033[0;32m✓ Task executed in {elapsed:.1f}s\033[0m")
            print(f"    Response: {text[:100]}")
        else:
            print(f"    \033[0;33m⚠ Got empty response\033[0m")
    except Exception as e:
        print(f"    \033[0;31m✗ Task failed: {e}\033[0m")

    print()

PYEOF

    echo ""
    echo -e "${BOLD}If any tests failed:${RESET}"
    echo "  make fleet-status     # Detailed per-node diagnostics"
    echo "  make fleet-firewall   # Check firewall rules"
    echo ""
}

# =============================================================================
# COMMAND: copy-config — helper to scp fleet.yaml to a remote node
# =============================================================================
cmd_copy() {
    local REMOTE_HOST="${1:-}"
    [[ -n "$REMOTE_HOST" ]] || die "Usage: make fleet-copy HOST=<ip>"
    [[ -f "$FLEET_CONFIG" ]] || die "No fleet config. Run 'make fleet-init' first."

    FLEET_TOKEN=$(grep 'token:' "$FLEET_CONFIG" | head -1 | awk '{print $2}' | tr -d '"')

    log_head "Copying fleet config to $REMOTE_HOST"

    log_step "Copying config/fleet.yaml"
    scp "$FLEET_CONFIG" "$REMOTE_HOST:~/devops-expert-local-ai/config/fleet.yaml"
    log_ok "fleet.yaml copied"

    log_step "Setting agent token in remote .env"
    ssh "$REMOTE_HOST" "cd ~/devops-expert-local-ai && \
        grep -q '^AICP_AGENT_SECRET=' .env 2>/dev/null && \
        sed -i 's|^AICP_AGENT_SECRET=.*|AICP_AGENT_SECRET=$FLEET_TOKEN|' .env || \
        echo 'AICP_AGENT_SECRET=$FLEET_TOKEN' >> .env"
    log_ok "Agent token set on remote"

    # Copy P2P token if it exists
    local P2P_TOKEN
    P2P_TOKEN=$(grep '^LOCALAI_P2P_TOKEN=' .env 2>/dev/null | cut -d= -f2-)
    if [[ -n "$P2P_TOKEN" ]]; then
        log_step "Setting LocalAI P2P token on remote"
        # P2P tokens can be very long (base64 YAML blob), so use a temp file
        local tmp_token
        tmp_token=$(mktemp)
        echo "$P2P_TOKEN" > "$tmp_token"
        scp "$tmp_token" "$REMOTE_HOST:/tmp/aicp-p2p-token.tmp"
        rm -f "$tmp_token"
        ssh "$REMOTE_HOST" "cd ~/devops-expert-local-ai && \
            P2P_VAL=\$(cat /tmp/aicp-p2p-token.tmp) && \
            rm -f /tmp/aicp-p2p-token.tmp && \
            if grep -q '^LOCALAI_P2P_TOKEN=' .env 2>/dev/null; then \
                sed -i \"s|^LOCALAI_P2P_TOKEN=.*|LOCALAI_P2P_TOKEN=\$P2P_VAL|\" .env; \
            else \
                echo '' >> .env; \
                echo \"LOCALAI_P2P_TOKEN=\$P2P_VAL\" >> .env; \
                echo 'LOCALAI_P2P_NETWORK_ID=aicp-fleet' >> .env; \
            fi"
        log_ok "P2P token set on remote"
    else
        log_info "No P2P token in .env — run 'make p2p-token' first if you want P2P"
    fi

    echo ""
    echo -e "${BOLD}Done. Now on $REMOTE_HOST:${RESET}"
    echo "  cd ~/devops-expert-local-ai"
    echo "  make local-down && make local-up-p2p    # Start LocalAI with P2P"
    echo "  make agent-up                           # Start fleet agent"
    echo ""
}

# =============================================================================
# COMMAND: p2p-token — fetch, save, and display the LocalAI P2P token
# =============================================================================
cmd_p2p_token() {
    local LOCALAI_PORT="${PORT:-8090}"

    log_head "LocalAI P2P Token"

    # Try to fetch from running instance
    local P2P_TOKEN=""
    P2P_TOKEN=$(curl -sf "http://localhost:$LOCALAI_PORT/api/p2p/token" 2>/dev/null || \
                 curl -sf "http://localhost:$LOCALAI_PORT/p2p/token" 2>/dev/null || true)

    if [[ -z "$P2P_TOKEN" || ${#P2P_TOKEN} -lt 50 ]]; then
        # Maybe LocalAI is running but not in P2P mode, or not running at all
        if curl -sf "http://localhost:$LOCALAI_PORT/v1/models" >/dev/null 2>&1; then
            log_fail "LocalAI is running but P2P token endpoint returned nothing."
            log_info "LocalAI must be started in P2P mode first:"
            log_info "  make local-down && make local-up-p2p"
            log_info "Then run: make p2p-token"
        else
            log_fail "LocalAI is not running."
            log_info "Start it in P2P mode:"
            log_info "  make local-up-p2p"
            log_info "Then run: make p2p-token"
        fi
        exit 1
    fi

    log_ok "P2P token fetched from LocalAI (${#P2P_TOKEN} chars)"

    # Save to .env
    if grep -q '^LOCALAI_P2P_TOKEN=' .env 2>/dev/null; then
        sed -i "s|^LOCALAI_P2P_TOKEN=.*|LOCALAI_P2P_TOKEN=$P2P_TOKEN|" .env
    else
        echo "" >> .env
        echo "# ── LocalAI P2P (fetched from running instance) ────────────────────────────" >> .env
        echo "LOCALAI_P2P_TOKEN=$P2P_TOKEN" >> .env
        echo "LOCALAI_P2P_NETWORK_ID=aicp-fleet" >> .env
    fi
    log_ok "Saved to .env"

    echo ""
    echo -e "${BOLD}Next: distribute to other fleet nodes:${RESET}"
    echo "  make fleet-copy HOST=<ip>    (copies fleet.yaml + P2P token to remote)"
    echo ""
    echo "  Then on the remote machine:"
    echo "    make local-down && make local-up-p2p"
    echo ""
}

# =============================================================================
# COMMAND: firewall — print firewall rules for all AICP ports
# =============================================================================
cmd_firewall() {
    log_head "AICP Firewall Rules"

    echo ""
    echo -e "${BOLD}Ports used by AICP:${RESET}"
    echo ""
    echo "  Port   Service           Protocol  Notes"
    echo "  ─────  ────────────────  ────────  ─────────────────────────────────────"
    echo "  8090   LocalAI API       TCP/HTTP  Model inference (chat, embed, TTS, etc.)"
    echo "  9100   AICP Agent        TCP/HTTP  Fleet communication between nodes"
    echo "  9876   LocalAI P2P       TCP       libp2p peer discovery + federated inference"
    echo ""
    echo "  All ports need to be open for INBOUND TCP on every fleet machine."
    echo ""

    # Detect environment
    local is_wsl=0
    grep -qi microsoft /proc/version 2>/dev/null && is_wsl=1

    # Detect Windows network profile
    local net_profile="Private,Public"
    if [[ "$is_wsl" -eq 1 ]]; then
        local detected_profile
        detected_profile=$(powershell.exe -NoProfile -Command \
            "(Get-NetConnectionProfile | Select-Object -First 1).NetworkCategory" \
            2>/dev/null | tr -d '\r\n')
        if [[ -n "$detected_profile" ]]; then
            echo -e "  ${YELLOW}⚠ Your Windows network is classified as: ${BOLD}${detected_profile}${RESET}"
            echo "  Firewall rules MUST match this profile or traffic will be silently dropped."
            if [[ "$detected_profile" == "Public" ]]; then
                echo -e "  ${YELLOW}  Tip: To switch to Private (recommended for home LAN):${RESET}"
                echo "    Set-NetConnectionProfile -InterfaceAlias 'Ethernet' -NetworkCategory Private"
            fi
            echo ""
            net_profile="$detected_profile"
        fi
    fi

    echo -e "${BOLD}═══ Option A: Windows Firewall (built-in) ═══${RESET}"
    echo ""
    echo "  Run these in an ${BOLD}Administrator PowerShell${RESET}:"
    echo ""
    echo "  # Allow LocalAI API (port 8090)"
    echo "  New-NetFirewallRule -DisplayName 'AICP - LocalAI API' \\"
    echo "    -Direction Inbound -Protocol TCP -LocalPort 8090 \\"
    echo "    -Action Allow -Profile $net_profile"
    echo ""
    echo "  # Allow AICP Agent (port 9100)"
    echo "  New-NetFirewallRule -DisplayName 'AICP - Agent Daemon' \\"
    echo "    -Direction Inbound -Protocol TCP -LocalPort 9100 \\"
    echo "    -Action Allow -Profile $net_profile"
    echo ""
    echo "  # Allow LocalAI P2P (port 9876)"
    echo "  New-NetFirewallRule -DisplayName 'AICP - LocalAI P2P' \\"
    echo "    -Direction Inbound -Protocol TCP -LocalPort 9876 \\"
    echo "    -Action Allow -Profile $net_profile"
    echo ""
    echo "  # Allow ping (ICMP) — used by fleet-status diagnostics"
    echo "  New-NetFirewallRule -DisplayName 'AICP - Ping (ICMP)' \\"
    echo "    -Direction Inbound -Protocol ICMPv4 -IcmpType 8 \\"
    echo "    -Action Allow -Profile $net_profile"
    echo ""
    echo "  To verify:"
    echo "  Get-NetFirewallRule -DisplayName 'AICP*' | Format-Table DisplayName,Enabled,Direction,Profile"
    echo ""
    echo "  To remove later:"
    echo "  Remove-NetFirewallRule -DisplayName 'AICP*'"
    echo ""

    echo -e "${BOLD}═══ Option B: ESET Firewall ═══${RESET}"
    echo ""
    echo "  If ESET Smart Security / Internet Security manages your firewall,"
    echo "  Windows Firewall rules may be IGNORED. Configure in ESET instead:"
    echo ""
    echo "  1. Open ESET → Setup → Network protection → Firewall"
    echo "  2. Click 'Configure rules...' (or 'Interactive mode' rules)"
    echo "  3. Add THREE rules:"
    echo ""
    echo "     Rule 1: AICP - LocalAI API"
    echo "       Direction:   Inbound"
    echo "       Protocol:    TCP"
    echo "       Local port:  8090"
    echo "       Action:      Allow"
    echo "       Profile:     Home / Trusted network"
    echo ""
    echo "     Rule 2: AICP - Agent Daemon"
    echo "       Direction:   Inbound"
    echo "       Protocol:    TCP"
    echo "       Local port:  9100"
    echo "       Action:      Allow"
    echo "       Profile:     Home / Trusted network"
    echo ""
    echo "     Rule 3: AICP - LocalAI P2P"
    echo "       Direction:   Inbound"
    echo "       Protocol:    TCP"
    echo "       Local port:  9876"
    echo "       Action:      Allow"
    echo "       Profile:     Home / Trusted network"
    echo ""
    echo "  Tip: If ESET is in Interactive mode, it will prompt when a"
    echo "  connection comes in — choose 'Allow' and 'Create rule'."
    echo ""
    echo "  IMPORTANT: If ESET manages your firewall, Windows Firewall rules"
    echo "  are IGNORED. Check which one is active:"
    echo "    ESET → Setup → Network protection → see if Firewall shows 'Active'"
    echo ""
    echo "  Also ensure your LAN is in ESET's Trusted zone:"
    echo "    ESET → Setup → Network protection → Connected networks"
    echo "    → Set your home network to 'Home / Office' (not 'Public')"
    echo ""

    if [[ "$is_wsl" -eq 1 ]]; then
        echo -e "${BOLD}═══ WSL2 Note ═══${RESET}"
        echo ""
        echo "  Docker auto-exposes 8090 to LAN (dual-stack binding)."
        echo "  Agent (9100) and P2P (9876) run inside WSL, so they need forwarding:"
        echo ""
        echo "    make wsl-forward          # Forward 9100 + 9876"
        echo "    make wsl-forward-check    # Verify current forwards"
        echo ""
        echo "  Port forward + firewall rule are BOTH needed for 9100 and 9876."
        echo ""
    fi

    echo -e "${BOLD}═══ Linux (bare metal, no WSL) ═══${RESET}"
    echo ""
    echo "  If running on native Linux, use iptables/ufw:"
    echo ""
    echo "  # ufw (Ubuntu/Debian)"
    echo "  sudo ufw allow 8090/tcp comment 'AICP - LocalAI API'"
    echo "  sudo ufw allow 9100/tcp comment 'AICP - Agent Daemon'"
    echo "  sudo ufw allow 9876/tcp comment 'AICP - LocalAI P2P'"
    echo ""
    echo "  # iptables (any distro)"
    echo "  sudo iptables -A INPUT -p tcp --dport 8090 -j ACCEPT"
    echo "  sudo iptables -A INPUT -p tcp --dport 9100 -j ACCEPT"
    echo "  sudo iptables -A INPUT -p tcp --dport 9876 -j ACCEPT"
    echo ""

    # Quick connectivity test hint
    echo -e "${BOLD}═══ Quick test from another machine ═══${RESET}"
    echo ""
    local MY_IP
    MY_IP=$(detect_local_ip)
    echo "  From the other machine, run:"
    echo "    curl -sf http://$MY_IP:8090/v1/models    # Should return JSON"
    echo "    curl -sf http://$MY_IP:9100/health        # Should return {\"status\":\"ok\"}"
    echo ""
}

# =============================================================================
# Dispatch
# =============================================================================
CMD="${1:-}"
shift || true

case "$CMD" in
    init)      cmd_init ;;
    join)      cmd_join "${HOST:-${1:-}}" "${PORT:-$DEFAULT_PORT}" "${FLEET_NAME:-}" ;;
    status)    cmd_status ;;
    test)      cmd_test ;;
    copy)      cmd_copy "${HOST:-${1:-}}" ;;
    p2p-token) cmd_p2p_token ;;
    firewall)  cmd_firewall ;;
    *)
        echo "Usage: scripts/fleet.sh <command>"
        echo ""
        echo "Commands:"
        echo "  init                 Generate fleet token + config for this node"
        echo "  join                 Add a remote node (HOST=<ip>)"
        echo "  status               Check all fleet nodes"
        echo "  test                 Run a test task on each node"
        echo "  copy                 SCP fleet config to a remote node (HOST=<ip>)"
        echo "  p2p-token            Fetch P2P token from LocalAI and save to .env"
        echo "  firewall             Show firewall rules for all AICP ports"
        exit 1
        ;;
esac
